# -*- coding: utf-8 -*-
"""market_sentiment_dashboard.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17bTZzyadixe3E1dqX6gAAS_K2fGuvo0x
"""

import streamlit as st
import pandas as pd
import plotly.express as px
import numpy as np

# ================================================================= #
# PAGE CONFIGURATION & HEADER                                       #
# ================================================================= #
st.set_page_config(layout="wide", page_title="Trader Performance Dashboard")

st.title("📊 Trader Performance vs Market Sentiment")
st.markdown("An interactive dashboard exploring how market sentiment (Fear/Greed) impacts trader profitability and behavior on Hyperliquid.")

# ================================================================= #
# DATA LOADING (CACHED FOR PERFORMANCE)                             #
# ================================================================= #
@st.cache_data
def load_and_prep_data():
# ==============================================================================
# Read the compressed ZIP file directly into pandas to bypass file size limits
# ==============================================================================
    trader_df = pd.read_csv("historical_data.zip", low_memory=False)
    sentiment_df = pd.read_csv("fear_greed_index.csv")

    # 1. Clean missing values
    trader_df.dropna(inplace=True)

    # 2. Convert and align dates
    trader_df['Date'] = pd.to_datetime(trader_df['Timestamp IST'], dayfirst=True, errors='coerce').dt.strftime('%Y-%m-%d')
    sentiment_df['Date'] = pd.to_datetime(sentiment_df['date']).dt.strftime('%Y-%m-%d')

    # 3. Merge datasets
    merged_df = pd.merge(trader_df, sentiment_df[['Date', 'classification', 'value']], on='Date', how='left')
    merged_df.dropna(subset=['classification'], inplace=True)

    # 4. Engineer basic metrics
    merged_df['Is_Win'] = (merged_df['Closed PnL'] > 0).astype(int)

    return merged_df

# Load the data
df = load_and_prep_data()

# ================================================================= #
# SIDEBAR FILTERS                                                   #
# ================================================================= #
st.sidebar.header("Filter Options")
all_sentiments = df['classification'].unique().tolist()
selected_sentiment = st.sidebar.multiselect(
    "Select Market Sentiment",
    all_sentiments,
    default=all_sentiments
)

# Apply filters
filtered_df = df[df['classification'].isin(selected_sentiment)]

# ================================================================= #
# TOP LEVEL METRICS                                                 #
# ================================================================= #
st.markdown("### 🏆 Key Metrics (Filtered)")
col1, col2, col3 = st.columns(3)

total_trades = filtered_df.shape[0]
win_rate = (filtered_df['Is_Win'].mean() * 100) if total_trades > 0 else 0
avg_pnl = filtered_df['Closed PnL'].mean() if total_trades > 0 else 0

col1.metric("Total Trades", f"{total_trades:,}")
col2.metric("Overall Win Rate", f"{win_rate:.1f}%")
col3.metric("Avg PnL per Trade", f"${avg_pnl:.2f}")

st.divider()

# ================================================================= #
# CHARTS & VISUALIZATIONS                                           #
# ================================================================= #
col_chart1, col_chart2 = st.columns(2)

with col_chart1:
    st.markdown("#### Average PnL by Sentiment")
    if not filtered_df.empty:
        perf = filtered_df.groupby('classification')['Closed PnL'].mean().reset_index()
        fig_pnl = px.bar(perf, x='classification', y='Closed PnL', color='classification', text_auto='.2f')
        fig_pnl.update_layout(xaxis_title="Sentiment Classification", yaxis_title="Average PnL ($)")
        st.plotly_chart(fig_pnl, use_container_width=True)

with col_chart2:
    st.markdown("#### Long (BUY) Bias by Sentiment")
    if not filtered_df.empty:
        behavior = filtered_df.groupby('classification').agg(
            Long_Ratio=('Side', lambda x: (x == 'BUY').sum() / len(x))
        ).reset_index()
        fig_bias = px.bar(behavior, x='classification', y='Long_Ratio', color='classification', text_auto='.1%')
        fig_bias.update_layout(xaxis_title="Sentiment Classification", yaxis_title="Long Ratio (%)")
        st.plotly_chart(fig_bias, use_container_width=True)

st.divider()

st.markdown("#### 📈 Capital Deployment (Average Trade Size)")
if not filtered_df.empty:
    size_df = filtered_df.groupby('classification')['Size USD'].mean().reset_index()
    fig_size = px.bar(size_df, x='classification', y='Size USD', color='classification', text_auto='.0f')
    fig_size.update_layout(xaxis_title="Sentiment Classification", yaxis_title="Average Trade Size (USD)")
    st.plotly_chart(fig_size, use_container_width=True)
